version: 2
  jobs:
    build:
      docker:
        - image: circleci/python:latest
      context: secrets
      steps:
        - run:
            name: "show me an environment variable"
            command: echo ${secret_token}