workflows:
  version: 2
  this-workflow:
    jobs:
      - build:
          context: secrets
          docker:
            - image: circleci/python:latest
          steps:
            - run:
                name: "show me an environment variable"
                command: echo ${secret_token}